import { $, api, currentUser, toast, go, escapeHtml, clearCurrentUserCache } from '../shared.mjs';

export async function initDashboard(){
  if(!$('[data-user-name]')&&!$('[data-resume-count]')&&!$('[data-resume-list]')&&!$('[data-resume-library]'))return;
  const user=await currentUser(); if(!user)return go('../auth/login.html');
  const name=$('[data-user-name]'); if(name) name.textContent=user.name.split(' ')[0];
  const plan=$('[data-user-plan]'); if(plan)plan.textContent={free:'Gratuito',basic:'Básico',premium:'Premium'}[user.plan];
  try{const [r,u]=await Promise.all([api('/resumes'),api('/usage')]); const count=$('[data-resume-count]');if(count)count.textContent=r.resumes.length;const usage=$('[data-usage]');if(usage)usage.textContent=u.remaining.exports===null?'Ilimitado':`${u.remaining.exports}/${u.plan.dailyLimit}`;const capacity=$('[data-resume-capacity]');if(capacity){const c=u.resumeCapacity;capacity.textContent=c.limit===null?`${c.current} currículos salvos · sem limite`: `Você tem ${c.current} de ${c.limit} currículos salvos. ${c.available?`Pode criar mais ${c.available}.`: 'Para criar outro, exclua um currículo ou confira os planos.'}`}renderResumeList(r.resumes,!!$('[data-resume-library]'));}catch(err){toast(err.message,'error')}
}
function renderResumeList(resumes,library=false){const box=$('[data-resume-library]')||$('[data-resume-list]');if(!box)return;const list=library?resumes:resumes.slice(0,3);box.innerHTML=list.length?list.map(r=>`<article class="resume-row"><div class="resume-info"><div class="resume-thumb"></div><div><strong>${escapeHtml(r.title)}</strong><span>${new Date(r.updatedAt).toLocaleDateString('pt-BR')} · ${escapeHtml(templateName(r.template))}</span></div></div><div class="resume-actions"><a class="button button-secondary button-small" href="../builder/editor.html?id=${encodeURIComponent(r.id)}">Editar e visualizar</a><button class="button button-ghost button-small delete-resume" type="button" data-resume-delete="${escapeHtml(r.id)}">Excluir</button></div></article>`).join(''):`<div class="empty-resumes"><div class="empty-resume-icon">▤</div><h2>Nenhum currículo salvo ainda</h2><p>Crie um currículo ou escolha um modelo para começar.</p><div class="resume-actions"><a class="button button-primary button-small" href="../builder/novo-curriculo.html">Criar currículo</a><a class="button button-secondary button-small" href="../builder/modelos.html">Escolher modelo</a></div></div>`;box.onclick=async event=>{const button=event.target.closest('[data-resume-delete]');if(!button)return;if(!confirm('Excluir este currículo? Essa ação remove o currículo e não pode ser desfeita.'))return;button.disabled=true;try{await api('/resumes/'+encodeURIComponent(button.dataset.resumeDelete),{method:'DELETE'});toast('Currículo excluído. Uma vaga foi liberada.','success');location.reload()}catch(error){button.disabled=false;toast(error.message,'error')}}}
function templateName(key){return({modern:'Moderno',classic:'Clássico',minimal:'Minimal',executive:'Executivo',creative:'Criativo'})[key]||'Moderno'}

export async function initLogout(){$$('[data-logout]').forEach(btn=>btn.addEventListener('click',async()=>{btn.disabled=true;try{await api('/auth/logout',{method:'POST'});clearCurrentUserCache();go('../../index.html')}catch(error){toast('Não foi possível sair agora. Verifique a conexão e tente novamente.','error');btn.disabled=false}}))}

