import { $, $$, api, toast, escapeHtml } from '../shared.mjs';

function addEditorEntry(form,type,item={}){const target=type==='experience'?'experiences':'education', fields=type==='experience'?[['role','Cargo'],['company','Empresa']]:[['course','Curso ou formação'],['school','Instituição']];const box=document.createElement('fieldset');box.className='editor-entry';box.dataset.editorEntry=type;box.innerHTML=`<legend>${type==='experience'?'Experiência':'Formação'}</legend>${fields.map(([key,label])=>`<label class="form-field"><span>${label}</span><input data-entry-field="${key}"></label>`).join('')}<label class="form-field"><span>Data de início</span><input type="date" data-entry-field="startDate"></label><label class="form-field"><span>Data de término</span><input type="date" data-entry-field="endDate"></label><label class="form-field current-field"><input type="checkbox" data-current><span>${type==='experience'?'Trabalho aqui atualmente':'Estou estudando atualmente'}</span></label>${type==='experience'?'<label class="form-field"><span>Atividades e resultados</span><textarea data-entry-field="description" rows="3"></textarea></label>':''}${item.period&&!item.startDate&&!item.endDate?`<label class="form-field"><span>Período já cadastrado (formato antigo)</span><input data-entry-field="period"></label>`:''}<button type="button" class="button button-ghost button-small" data-editor-remove>Remover</button>`;$(target==='experiences'?'[data-editor-experiences]':'[data-editor-education]',form).append(box);for(const [key,value] of Object.entries(item)){const field=$(`[data-entry-field="${key}"]`,box);if(field)field.value=value||''}const start=$('[data-entry-field="startDate"]',box),end=$('[data-entry-field="endDate"]',box),current=$('[data-current]',box);current.checked=!!item.current;end.disabled=current.checked;if(start.value)end.min=start.value;}
function parseLegacyDate(value){if(!value)return '';if(/^\d{4}-\d{2}-\d{2}$/.test(value))return value;if(/^\d{4}-\d{2}$/.test(value))return `${value}-01`;const m=String(value).match(/(\d{1,2})\s*\/\s*(\d{4})/);if(m)return `${m[2]}-${m[1].padStart(2,'0')}-01`;return '';}
function fillEditor(form,r){const d=r.data||{}; for(const key of ['title','accent','template'])if(form.elements[key])form.elements[key].value=r[key]||'';for(const key of ['name','role','email','phone','city','summary'])if(form.elements[key])form.elements[key].value=d[key]||''; if(form.elements.skills)form.elements.skills.value=(d.skills||[]).join(', '); (d.experiences||[]).forEach(item=>addEditorEntry(form,'experience',{...item,startDate:item.startDate||parseLegacyDate(item.period),endDate:item.endDate||''}));(d.education||[]).forEach(item=>addEditorEntry(form,'education',{...item,startDate:item.startDate||parseLegacyDate(item.period),endDate:item.endDate||''}));}
function collectEditor(form){const d={};for(const key of ['name','role','email','phone','city','summary'])d[key]=form.elements[key]?.value.trim()||'';d.skills=(form.elements.skills?.value||'').split(',').map(x=>x.trim()).filter(Boolean);const entries=type=>$$(`[data-editor-entry="${type}"]`,form).map(row=>{const item={};$$('[data-entry-field]',row).forEach(field=>item[field.dataset.entryField]=field.value.trim());item.startDate=item.startDate||'';item.endDate=item.endDate||'';item.current=$('[data-current]',row).checked;return item}).filter(item=>Object.entries(item).some(([key,value])=>!['current','startDate','endDate'].includes(key)&&value)||item.startDate);d.experiences=entries('experience');d.education=entries('education');return d;}
function formatPeriod(item){if(item.period)return item.period;const fmt=value=>{if(!value)return '';const date=new Date(`${value.slice(0,10)}T00:00:00`);return Number.isNaN(date.valueOf())?'':date.toLocaleDateString('pt-BR',{month:'short',year:'numeric'})};const start=fmt(item.startDate),end=item.current?'Atual':fmt(item.endDate);return [start,end].filter(Boolean).join(' – ')}
async function saveEditor(form,r,{quiet=false}={}){const button=$('[data-save]');if(button)button.disabled=true;try{const out=await api('/resumes/'+r.id,{method:'PATCH',body:JSON.stringify({title:form.elements.title.value,template:form.elements.template.value,accent:form.elements.accent.value,data:collectEditor(form)})});if(!quiet)toast('Currículo salvo.','success');return out.resume}catch(e){if(!quiet)toast(e.message,'error');return null}finally{if(button)button.disabled=false}}
function renderPaper(form){const d=collectEditor(form), paper=$('[data-paper]');if(!paper)return;paper.dataset.template=form.elements.template.value;paper.style.setProperty('--accent',form.elements.accent.value);paper.innerHTML=`<div class="paper-head"><h1>${escapeHtml(d.name||'Seu nome')}</h1><p>${escapeHtml(d.role||'Cargo desejado')}</p><small>${escapeHtml([d.email,d.phone,d.city].filter(Boolean).join(' · '))}</small></div>${d.summary?`<section><h2>Resumo</h2><p>${escapeHtml(d.summary)}</p></section>`:''}${d.experiences.length?`<section><h2>Experiência</h2>${d.experiences.map(x=>`<div><strong>${escapeHtml(x.role)}</strong><p>${escapeHtml([x.company,formatPeriod(x)].filter(Boolean).join(' · '))}</p><p>${escapeHtml(x.description||'')}</p></div>`).join('')}`:''}${d.education.length?`<section><h2>Formação</h2>${d.education.map(x=>`<div><strong>${escapeHtml(x.course)}</strong><p>${escapeHtml([x.school,formatPeriod(x)].filter(Boolean).join(' · '))}</p></div>`).join('')}`:''}${d.skills.length?`<section><h2>Habilidades</h2><p>${d.skills.map(x=>`<span class="skill-chip">${escapeHtml(x)}</span>`).join(' ')}</p></section>`:''}`;}
async function exportResume(id){try{const html=await fetch('/api/resumes/'+id+'/export',{method:'POST',credentials:'include'}).then(async r=>{if(!r.ok)throw new Error((await r.json()).error);return r.text()});const w=window.open('','_blank');w.document.write(html);w.document.close()}catch(e){toast(e.message,'error')}}
async function shareResume(id){try{const r=await api('/resumes/'+id+'/share',{method:'POST'});await navigator.clipboard?.writeText(r.url);toast(`Link copiado: ${r.url}`,'success')}catch(e){toast(e.message,'error')}}

export { addEditorEntry, parseLegacyDate, fillEditor, collectEditor, formatPeriod, saveEditor, renderPaper, exportResume, shareResume };
